/*
 * Command_Constants.h
 *
 *  Created on: Aug 2, 2016
 *      Author: gazi
 */

#ifndef USB_SERIAL_CONSTANTS_H_
#define USB_SERIAL_CONSTANTS_H_

#define SET_SPEED_L 0
#define SET_SPEED_R 1
#define SET_SPEEDS 2

#define GET_SPEED_L 3
#define GET_SPEED_R 4

#define GET_POSITIONS 5
#define GET_POSITION_L 6
#define GET_POSITION_R 7

#define READ_ANALOG_INPUT_L 8
#define READ_ANALOG_INPUT_R 9
#define READ_FEEDBACK_L 10
#define READ_FEEDBACK_R 11

#define READ_PID_PROPORTIONAL_GAIN_X10_L 12
#define READ_PID_PROPORTIONAL_GAIN_X10_R 13
#define SET_PID_PROPORTIONAL_GAIN_L 14
#define SET_PID_PROPORTIONAL_GAIN_R 15

#define READ_PID_INTEGRAL_GAIN_X10_L 16
#define READ_PID_INTEGRAL_GAIN_X10_R 17
#define SET_PID_INTEGRAL_GAIN_L 18
#define SET_PID_INTEGRAL_GAIN_R 19

#define READ_PID_DIFFERENTIAL_GAIN_X10_L 20
#define READ_PID_DIFFERENTIAL_GAIN_X10_R 21
#define SET_PID_DIFFERENTIAL_GAIN_L 22
#define SET_PID_DIFFERENTIAL_GAIN_R 23

#define READ_PID_INTEGRAL_CAP_L 24
#define READ_PID_INTEGRAL_CAP_R 25
#define SET_PID_INTEGRAL_CAP_L 26
#define SET_PID_INTEGRAL_CAP_R 27

#define READ_TURNS_MIN_MAX_X100_L 28
#define READ_TURNS_MIN_MAX_X100_R 29
#define SET_TURNS_MIN_MAX_L 30
#define SET_TURNS_MIN_MAX_R 31

#define READ_DEFAULT_POSITION_VELOCITY_L 32
#define READ_DEFAULT_POSITION_VELOCITY_R 33
#define SET_DEFAULT_POSITION_VELOCITY_L 34
#define SET_DEFAULT_POSITION_VELOCITY_R 35

#define READ_CURRENT_LIMIT_X10_L 36
#define READ_CURRENT_LIMIT_X10_R 37
#define SET_CURRENT_LIMIT_L 38
#define SET_CURRENT_LIMIT_R 39

#define READ_MAX_POWER_FORWARD_L 40
#define READ_MAX_POWER_FORWARD_R 41
#define SET_MAX_POWER_FORWARD_L 42
#define SET_MAX_POWER_FORWARD_R 43

#define READ_MAX_POWER_REVERSE_L 44
#define READ_MAX_POWER_REVERSE_R 45
#define SET_MAX_POWER_REVERSE_L 46
#define SET_MAX_POWER_REVERSE_R 47

#define READ_MAX_SPEED_L 48
#define READ_MAX_SPEED_R 49
#define SET_MAX_SPEED_L 50
#define SET_MAX_SPEED_R 51

#define READ_ACCELERATION_X10_L 52
#define READ_ACCELERATION_X10_R 53
#define SET_ACCELERATION_L 54
#define SET_ACCELERATION_R 55

#define READ_DECELERATION_X10_L 56
#define READ_DECELERATION_X10_R 57
#define SET_DECELERATION_L 58
#define SET_DECELERATION_R 59

#define READ_ANALOG_INPUT_MIN_L 60
#define READ_ANALOG_INPUT_MIN_R 61
#define SET_ANALOG_INPUT_MIN_L 62
#define SET_ANALOG_INPUT_MIN_R 63

#define READ_ANALOG_INPUT_CENTER_L 64
#define READ_ANALOG_INPUT_CENTER_R 65
#define SET_ANALOG_INPUT_CENTER_L 66
#define SET_ANALOG_INPUT_CENTER_R 67

#define READ_ANALOG_INPUT_MAX_L 68
#define READ_ANALOG_INPUT_MAX_R 69
#define SET_ANALOG_INPUT_MAX_L 70
#define SET_ANALOG_INPUT_MAX_R 71

#define READ_ANALOG_INPUT_POLARITY_L 72
#define READ_ANALOG_INPUT_POLARITY_R 73
#define SET_ANALOG_INPUT_POLARITY_L 74
#define SET_ANALOG_INPUT_POLARITY_R 75

#define READ_ANALOG_INPUT_DEAD_BAND_L 76
#define READ_ANALOG_INPUT_DEAD_BAND_R 77
#define SET_ANALOG_INPUT_DEAD_BAND_L 78
#define SET_ANALOG_INPUT_DEAD_BAND_R 79

#define READ_CL_ERROR_DETECTION_L 80
#define READ_CL_ERROR_DETECTION_R 81
#define SET_CL_ERROR_DETECTION_L 82
#define SET_CL_ERROR_DETECTION_R 83

#define READ_BATTERY_VOLTAGE_X10 84

#define READ_MOTOR_COMMAND_L 85
#define READ_MOTOR_COMMAND_R 86

#define READ_CLOSED_LOOP_ERROR_L 87
#define READ_CLOSED_LOOP_ERROR_R 88

#define READ_MOTOR_AMPS_X10_L 89
#define READ_MOTOR_AMPS_X10_R 90

#define READ_MOTOR_POWER_L 91
#define READ_MOTOR_POWER_R 92

#define READ_RUNTIME_STATUS_L 93
#define READ_RUNTIME_STATUS_R 94

#define READ_FAULT_STATUS_L 95
#define READ_FAULT_STATUS_R 96

#define READ_TEMPERATURE_L 97
#define READ_TEMPERATURE_R 98

#define READ_TELEMETRY_STRING 99
#define SET_TELEMETRY_STRING 100

#define SAVE_TO_EEPROM 101

#define E_STOP_SOFT 102
#define RELEASE_E_STOP_SOFT 103

#define GO_L 104
#define GO_R 105

#define GET_DRIVE_VERSION 106



#endif /* USB_SERIAL_CONSTANTS_H_ */
